### ISSUE TITLE
Allow user to pass through their own credentials

### ISSUE THREAD

**Issue by mcloonan** [googleads/google-ads-ruby#101]
See for example: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/services/account_budget_service_client.rb#L78

The lib currently only accepts a refresh token and passes it along as part of the updater_proc, but we could allow the user to specify their credentials in any of the valid formats. We should add a config option to specify this with any custom value the user sets.

**Comment by evgeniy-b** [comment]
It would also be great to have a possibility to provide with own interceptors for service initialization since there is no way to inject [there](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/google_ads_client.rb#L139). Ideally (or additionally) in a global manner so this could be configured without modifying client/service initialization code and interceptor could be injected dynamically in tests (to fake requests).

**Comment by mcloonan** [comment]
Please file a separate issue for that request; we'll look into it separately. Thanks!
