### ISSUE TITLE
Build intermediary layer between existing calls and new gapic code

### ISSUE THREAD

**Issue by penelopezone** [googleads/google-ads-ruby#112]
All our calls are currently of the form `call(customer_id, something)`, the new gapic generated services take `request` like objects, we'll need to codegen out a translation layer so we don't break existing users

/cc @mcloonan @AnashOommen

**Comment by mcloonan** [comment]
We need to make sure that we allow users to work directly with the requests if they want, though, because they actually offer a lot more flexibility. There are some things in the API that are impossible to use in this lib right now because the current layer takes away any ability to interact directly with the request.

**Comment by samphippen** [comment]
👍 I'll prototype out what it'll look like to allow both
