### ISSUE TITLE
Querying campaign drafts using draft_id isn't working

### ISSUE THREAD

**Issue by pagipunit** [googleads/google-ads-ruby#155]
I created campaign 2042698994 and then created a draft campaign using the CampaignDraftService.MutateCampaignDrafts , the service call return me  [<Google::Ads::GoogleAds::V1::Services::MutateCampaignDraftResult: resource_name: "customers/4983552381/campaignDrafts/2042698994~281474976710656">]

As per documentation this is of the format 
customers/{customer_id}/campaignDrafts/{base_campaign_id}~{draft_id}

When I query campaign drafts using the draft_id=281474976710656 I get a totally unrelated draft 

#<Object:0x00007f933463b748 @external_id="281474976710656", @resource_name="281474976710656", @status=:REMOVED, @draft_id=281474976710656, @base_campaign="699490231", @name="Test Campaign 50604-exp_3985", @draft_campaign="281475676200887", @has_experiment_running=false, @long_running_operation=nil>

**Comment by samphippen** [comment]
@pagipunit are you using `GoogleAdsService` `search` to make this query or `CampaignDraftService`  `get_campaign_draft` to get the data back?

**Comment by pagipunit** [comment]
@samphippen , I'm using GoogleAdsService to query CampaignDrafts

**Comment by pagipunit** [comment]
@samphippen do you have any update on this?

**Comment by mcloonan** [comment]
For product requests like this you're better off asking on our API forum: https://groups.google.com/forum/#!forum/adwords-api

To answer this specific question, please make sure you use a PARAMETERS clause to indicate that drafts can be returned. You should only do this in requests where you are specifically interested in drafts, because it does cause the query to be slower. See: https://developers.google.com/google-ads/api/docs/query/structure#parameters
