### ISSUE TITLE
The error code is not in this version.

### ISSUE THREAD

**Issue by jairobluecaribu** [googleads/google-ads-ruby#298]
Hello,
I´ve got this issue when I try to create and Account.

data exception:
Message -> The error code is not in this version.
Tipo -> request_error Código -> UNKNOWN

/usr/local/rvm/gems/ruby-2.5.1/gems/google-ads-googleads-10..0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:67:in `rescue in request_response'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-ads-googleads-10.0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:63:in `request_response'
/usr/local/rvm/gems/ruby-2.5.1/gems/grpc-1.37.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
/usr/local/rvm/gems/ruby-2.5.1/gems/grpc-1.37.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-ads-googleads-10.0.0/lib/google/ads/google_ads/interceptors/logging_interceptor.rb:53:in `request_response'
/usr/local/rvm/gems/ruby-2.5.1/gems/grpc-1.37.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
/usr/local/rvm/gems/ruby-2.5.1/gems/grpc-1.37.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:173:in `block in request_response'
/usr/local/rvm/gems/ruby-2.5.1/gems/gapic-common-0.3.4/lib/gapic/grpc/service_stub/rpc_call.rb:121:in `call'
/usr/local/rvm/gems/ruby-2.5.1/gems/gapic-common-0.3.4/lib/gapic/grpc/service_stub.rb:156:in `call_rpc'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-ads-googleads-10.0.0/lib/google/ads/google_ads/v6/services/customer_service/client.rb:409:in `create_customer_client'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-ads-googleads-10.0.0/lib/google/ads/google_ads/service_wrapper.rb:50:in `public_send'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-ads-googleads-10.0.0/lib/google/ads/google_ads/service_wrapper.rb:50:in `method_missing'

**Comment by mcloonan** [comment]
This is a normal API response when the error code either is erroneously not included in the public protos or is from a version of the API that is ahead of the version being used for the current call (such as an error for v6 but you made the call using v5).

If you need help troubleshooting issues like this which are generic to the API rather than specific to the Ruby library, you can reach out on [this forum](https://groups.google.com/forum/#!forum/adwords-api) to our dedicated support team.
