### ISSUE TITLE
Developers site Ruby guide link is dead

### ISSUE THREAD

**Issue by lyzhao** [googleads/google-ads-ruby#299]
Developers site Ruby guide in the README links to a `Service Unavailable` page.

**Comment by mcloonan** [comment]
The link works fine for me. Try in an incognito tab with any ad blocker disabled and let me know if you can access the docs that way. If you still can't, please let me know what URL it is that the link is pointing to so I can see if maybe there's a different link that you clicked vs. the one I did.

**Comment by multiplegeorges** [comment]
I was having the same issue as @lyzhao and I investigated the error in the Network tab of Chrome's dev tools.

Turns out there was a service worker registered in my browser that was intercepting the request and returning 503. 

Unregistering that service worker allowed me to successfully load the docs.
