### ISSUE TITLE
Usage of dynamic credentials throws error

### ISSUE THREAD

**Issue by adambedford** [googleads/google-ads-ruby#308]
Hi there,

I'm just getting started with this library so please excuse this issue for what is likely a perfectly legitimate scenario. I'm trying to use dynamic credentials (We're using Omniauth to get a token and refresh token) and unsure how to configure this client.

I'm setting up the client as follows:

```ruby
    Google::Ads::GoogleAds::GoogleAdsClient.new do |config|
      config.client_id = ENV["GOOGLE_CLIENT_ID"]
      config.client_secret = ENV["GOOGLE_CLIENT_SECRET"]
      config.refresh_token = service.refresh_token
    end
```

But don't see where to set the actual token (rather than the refresh token).

We're also not able to requests with the above config, instead getting this error `ArgumentError (Header values must be of type string or array)`, which I assume is because we're missing some config/headers.

Any guidance on how to configure this library with an Oauth token obtained elsewhere (Omniauth in this case) would be greatly appreciated!

**Comment by mcloonan** [comment]
Can you provide a more complete stack trace for the error you're getting?

The library wasn't really designed to support you providing your own access tokens. You should just specify a refresh token, client ID, and client secret and the library will handle access tokens automatically. If you want to inject your own access token you'd need to write your own `updater_proc` which is a callback that is called whenever a new access token is needed to fetch the next one (since access tokens can only live for up to one hour).
