### ISSUE TITLE
Implement a gem for tests?

### ISSUE THREAD

**Issue by goldylucks** [googleads/google-ads-ruby#346]
What is your recommended way to implement tests the interacts with the google ads API?

I didn't find any references on this repo or in the docs. Do you plan on releasing a gem to support that?
If not, I'll probably end up creating one :)
(Any guidance appreciated!)

our testing philosophy is testing everything E2E, meaning, instead of stubbing our own internal google ads class, we want to test, ideally, the http calls themselves.

Is that possible?
what do you think about it?

For that to be viable (and not have brittle tests) the Rest API should be stable. Is that the case? do you keep the endpoints the same across gem versions?

Also, is there a place I can see all the API calls that happens for a specific operation? (and their respective payload/respones?)

For example, there is a call for authenticating which happens on some (or all?) the operations.

So far we are stubbing all the internal methods of the ads client, i.e. 
```
      allow_any_instance_of(
        Google::Ads::GoogleAds::GoogleAdsClient
      ).to receive_message_chain(
        "service.campaign_budget.mutate_campaign_budgets"
      ).with(
        customer_id: account_id,
        operations: [
          have_attributes(
            create: have_attributes(
              name: include(name),
              amount_micros: amount_micros,
              delivery_method: :STANDARD,
            )
          )
        ]
      ) { 
        OpenStruct.new(
          results: [
            OpenStruct.new(resource_name: budget_resource_name)
          ]
        )
      }
```

but that's far from ideal

I feel a dedicated gem would be the way to go here.

Thoughts?

and thanks again for the great project! :rocket:

**Comment by goldylucks** [comment]
you guys are usually very responsive, what happened? :)

we work extensively with the gem but we have to band over backwards to test interactions with it, and I only assume this is something other consumers of this gem are facing

would be great to have a dedicate solution (which again, I'm happy to implement)

**Comment by xflesym** [comment]
Hi Adam,

Google Ads API currently only has one endpoint which is configured here in [google_ads_client.rb](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/google_ads_client.rb#L133)

If I understand correctly, what you described should be an http endpoint (which listens to gRPC request) built to mimic the actual API behavior. And when you have this test endpoint, you can have your test infrastructure pointing to this endpoint and perform testing. 

At this point we don't have plans to publish such an endpoint. I don't recommend you build one yourself either, because even though the endpoint address stays the same across versions, the underlying logic could change from version to version.

Therefore, I think the best bet to address your test goal is either the stubbing strategy which you already have, or use a test account to run E2E test (within the limitation of test account, such as no reporting data, etc.).

Hope this answers your question.

Thanks,
-Fei

**Comment by goldylucks** [comment]
Thanks for the detailed response @xflesym 

You say there's only one endpoint, tho in the [docs](https://developers.google.com/google-ads/api/rest/design/overview) I see for example this endpoint:

```
https://googleads.googleapis.com/v8/customers/1234567890:mutate
```

Isn't that an endpoint?

i.e. if I'm having a test, I would stub the http call to that endpoint, `https://googleads.googleapis.com/v8/customers/1234567890:mutate`, along with the response.

What do you think about that testing strategy?

**Comment by xflesym** [comment]
Yup what you see in the docs is an endpoint for **REST** interface.

Apologies I wasn't being clear. What I meant was for **gRPC** endpoint we only had that one in [google_ads_client.rb](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/google_ads_client.rb#L133)

Stubbing the http call works if your code makes purely REST calls to Google Ads API.

However, if you use the client library to make request, because the client library makes gRPC calls to the gRPC endpoint I mentioned, the http endpoint you stubbed wouldn't work.

**Comment by goldylucks** [comment]
ok, thanks for the response
