### ISSUE TITLE
Return Request-Id in Response

### ISSUE THREAD

**Issue by Jhowden** [googleads/google-ads-ruby#377]
**Describe the problem you are trying to solve:**
Right now, it seems like the only way to view the request-id is configure the logger on the GoogleAdsClient object. I don't want the entire output that automatically gets written to the configured logger because I want more flexibility into what gets logged based on the response.

**Describe the solution you'd like:**
I would like to see the request-id be returned in the response object so that it can easily be accessed. Furthermore, if you look at the decoded partial failure response, it has the request_id field but it is always blank despite the logs showing a request-id being returned.

For example here are the logs for a failed request:
```
10:17:30 AM	WARN	2022-02-02 10:17:30 -0600	reverb_core.rails	17640	{"message":"CID: 1756035958, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v9.services.GoogleAdsService/Search, IsFault: yes, Request ID: vGV3QoQ2PtN00tmAVqsPIw"}
```
And in the decoded partial failures I see:
```
[<Google::Ads::GoogleAds::V9::Errors::GoogleAdsFailure: errors: [<Google::Ads::GoogleAds::V9::Errors::GoogleAdsError: error_code: <Google::Ads::GoogleAds::V9::Errors::ErrorCode: conversion_upload_error: :UNPARSEABLE_GCLID>, message: "This Google Click ID could not be decoded.", trigger: <Google::Ads::GoogleAds::V9::Common::Value: string_value: "bad-glcid">, location: <Google::Ads::GoogleAds::V9::Errors::ErrorLocation: field_path_elements: [<Google::Ads::GoogleAds::V9::Errors::ErrorLocation::FieldPathElement: field_name: "conversions", index: 0>, <Google::Ads::GoogleAds::V9::Errors::ErrorLocation::FieldPathElement: field_name: "gclid">]>>], request_id: "">]
```

**Comment by mcloonan** [comment]
The request ID is returned in the trailing metadata of the request, not as part of the response, so I don't think there's anything we can do about that in terms of general library functionality.

You could always write your own interceptor and log or do whatever you want with the information. For reference, here's our logging interceptor to get you started: https://github.com/googleads/google-ads-ruby/blob/main/lib/google/ads/google_ads/interceptors/logging_interceptor.rb

If you do write a custom interceptor, you would not be able to use our convenience methods for generating service instances (since there's no API to inject a custom interceptor right now). But if this is a solution you think you'd like to pursue, we could look at adding the ability to use custom interceptors with our service generator in the future.

**Comment by crespire** [comment]
We hit this trying to capture request-id, and wanted to add a finding that might be helpful to folks who run into this in the future.

The underlying `gapic` clients already expose the `request-id` the idiomatic way: pass a block and read it off the operation's trailing metadata.

```ruby
service.upload_click_conversions(customer_id:, conversions:, partial_failure: true) do |_response, operation|
  request_id = operation.trailing_metadata["request-id"]
end
```

The problem is that this doesn't work when you go through `client.service.<service>` which is the documented entry point. `client.service.conversion_upload` returns a `ServiceWrapper`, and `ServiceWrapper#method_missing` only forwards a caller-supplied block on its non-RPC passthrough branch. On the actual RPC branches it builds the request and calls the `gapic` method without the block:

```ruby
# lib/google/ads/google_ads/service_wrapper.rb (v36.1.0)
unless rpc_inputs.include?(name)
  return service.public_send(name, *args, **kwargs, &blk)   # block forwarded
end
# ...
service.public_send(name, request, options)   # RPC branch — &blk dropped
service.public_send(name, request, nil)        # same here
```

So the block is silently swallowed, `gapic`'s `yield` response, `operation if block_given?` never fires, and there's no way to reach `operation.trailing_metadata` through the wrapper. That leaves the logger as the only way to see the `request-id`, which is exactly the limitation described here.

The fix looks like just forwarding `&blk` on those RPC branches (e.g. `service.public_send(name, request, options, &blk)`). It's purely additive — callers that don't pass a block are unaffected. We're currently working around it with a small prepend over `ServiceWrapper#method_missing` that does this, and it lets us read the `request-id` without any logging changes.

Here's a prepend you can drop into a Rails initializer (our context) that restores block forwarding (it mirrors `method_missing` from v36.1.0 — re-diff against `service_wrapper.rb` if you're on a different version):

```ruby
# config/initializers/google_ads_service_wrapper_block_forwarding.rb
require "google/ads/google_ads"

module GoogleAdsServiceWrapperBlockForwarding
  def method_missing(name, *args, **kwargs, &blk)
    return super unless rpc_inputs.include?(name)

    request = rpc_inputs.fetch(name).new

    if kwargs.include?(:request) || kwargs.include?(:options)
      options = kwargs.delete(:options)
      kwargs.fetch(:request, {}).each { |field, value| write_field(request, value, field) }
      service.public_send(name, request, options, &blk)
    elsif !kwargs.empty? && args.empty?
      kwargs.each { |field, value| write_field(request, value, field) }
      service.public_send(name, request, nil, &blk)
    elsif args.empty?
      service.public_send(name, request, nil, &blk)
    else
      super
    end
  end
end

Google::Ads::GoogleAds::ServiceWrapper.prepend(GoogleAdsServiceWrapperBlockForwarding)
```

With that in place, the block form above works through `client.service.<service>` and you get the `request-id` inline:

```ruby
client.service.conversion_upload.upload_click_conversions(customer_id:, conversions:, partial_failure: true) do |_response, operation|
  request_id = operation.trailing_metadata["request-id"]
end
```

**Comment by dorasun** [comment]
Hi @crespire, thanks for sending this workaround and detailed explanation! I've added the `&blk` arg to the `public_send` calls and deployed it to [v41.1.0](https://github.com/googleads/google-ads-ruby/releases/tag/google-ads-googleads%2Fv41.1.0). Hopefully this helps!
