### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by Bukenco** [googleads/google-ads-ruby#382]
Hello there

I add gem into the project. I have added configuration as well. Locally works fine, but when I deploy it on the development machine, then  I'm getting error: `/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- google/ads/google_ads/api_versions (LoadError)`

My configuration file:

`
require "google/ads/google_ads"

Google::Ads::GoogleAds::Config.new do |c|
  c.treat_deprecation_warnings_as_errors = false
  c.warn_on_all_deprecations = false

  c.developer_token = Rails.application.secrets.dev_token

  c.client_id = Rails.application.secrets.google_client_id
  c.client_secret = Rails.application.secrets.google_client_secret
  c.login_customer_id = Rails.application.secrets.google_login_customer_id

  c.log_level = 'WARN'
  c.log_target = STDOUT
end`

When I run `zeitwerk:check` on my local machine everything is fine.
When I run `zeitwerk:check` on development machine, I got the errors: `LoadError: cannot load such file -- google/ads/google_ads`

Any help?

**Comment by mcloonan** [comment]
This looks like it may be the same issue as from issue #355. What gem version are you using? Can you try using the most recently published gem and see if that resolves it?

**Comment by Bukenco** [comment]
I'm using version 10.0, but on my local machine 10.0 works fine too. Any other advice? Anyway I will try to update to latest version.

**Comment by mcloonan** [comment]
We had an issue where files weren't marked as executable that should be fixed as of 16.0.0. Please try that version of the gem.

I'm not sure how you could still be using 10.0.0 since that only supported up to v6 of the API, which has since been removed. The newest version of the gem will support the latest API versions as well. You should expect to update your gem version at least a few times a year to keep up to date with the latest API changes.

**Comment by Bukenco** [comment]
Hello again and thanks for you support. But here i have gem hell, when I'm trying to update gem at 16.0.0, then i have problem with faraday versions. One example is below:
`In Gemfile:
    carrierwave-azure_rm was resolved to 0.1.2, which depends on
      azure-storage (~> 0.12.1.preview) was resolved to 0.12.3.preview, which depends on
        faraday (~> 0.9)

    google-ads-googleads (~> 16.0) was resolved to 16.0.0, which depends on
      gapic-common (~> 0.6.0) was resolved to 0.6.0, which depends on
        faraday (~> 1.3)`

I tried to update faraday but it does not works, what can you advice?

**Comment by mcloonan** [comment]
The library `azure-storage` seems to depend on a version of faraday < 1.0, whereas we require >=1.3 but <2.0. Clearly, these are not compatible, so there's no single version of faraday that fits both requirements. `azure-storage` hasn't been updated since 2017, so it looks out of date.

I'm not sure there's a good way to resolve that short of finding an alternative to that other library. You could try forking it and updating the dependencies yourself, or reaching out to the owner to see if they're still around to make a new version with updated dependencies.
