### ISSUE TITLE
Empty results when migrate from the old Adwords to Google Ads Click View

### ISSUE THREAD

**Issue by afonsocdaniel** [googleads/google-ads-ruby#387]
Hello Team,
I'm working in the migration to the new Google Ads API, currently working in the migration process from CLICK_PERFORMANCE_REPORT to Click View report.

I have an issue when filter by a GCLID. For some reason, it always returns an empty list. I tried with more than one account and gclid.

GAQL:
```
click_view_query = <<~QUERY
  SELECT
        campaign.id,
        campaign.name,
        ad_group.name,
        d_group.id,
        click_view.area_of_interest.region,
        click_view.area_of_interest.city,
        segments.slot,
        click_view.keyword_info.text,
        click_view.keyword_info.match_type
  FROM click_view
  WHERE click_view.gclid = '#{CLICK_ID}'
  AND segments.date = '2022-04-11'
QUERY
```

Ruby Client:
```
result = @google_ads_client.service.google_ads.search(
customer_id: @account_id,
return_total_results_count: true,
query: click_view_query
)
```
Client version: 16.0
I would appreciate any help here.

**Comment by mcloonan** [comment]
This doesn't sound like a Ruby-library-specific problem; most likely there's either a problem with your query or a bug in the API with regards to filtering on that field. Either way, you would get a faster answer asking on the general Google Ads API forum: https://groups.google.com/g/adwords-api

**Comment by afonsocdaniel** [comment]
Thank you @mcloonan. I will ask in the google forum. I will close this issue, since it's not related to the Ruby Library.

**Comment by visrut7** [comment]
Hi @afonsocdaniel did you found the solution to your problem? Since I am facing the same issue and saw your thread on google groups: https://groups.google.com/g/adwords-api/c/VpstE82Zr60, but seems like community have not provided any public response there but if you were able to solve it then please let me know.

**Comment by visrut-at-handldigital** [comment]
Hi @afonsocdaniel did you found the solution to your problem? Since I am facing the same issue and saw your thread on google groups: https://groups.google.com/g/adwords-api/c/VpstE82Zr60, but seems like community have not provided any public response there but if you were able to solve it then please let me know.

**Comment by visrut-at-handldigital** [comment]
Apologies, it was my fault. I learned that it will only return a response if clicks had to happen for that date; otherwise, it will not. I am keeping this here for others if anyone faces the same issue.

Just keep one thing in mind change `segments.date`  value where the clicks have happened actually, to know that check the graph of `Ads` under your campaign

![image](https://github.com/user-attachments/assets/df5aeccc-7773-4b18-aeec-4516939cc702)
