### ISSUE TITLE
Deprecation about method of authentication 

### ISSUE THREAD

**Issue by cesarediaz** [googleads/google-ads-ruby#395]
**Is it sorted the deprecation authorization for the OOB flow in the last version of this gem?**

Hi guys, into accord to this [document](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#dates-oob)  from a google's blog we need to determine if our client oAuth library is using this OOB flow.

In our company we are using this gem in version 16.0 and all our config for authentication nowadays with google-ads-googleads version 16.0 relies in a file google_ads_config.rb similar to this next sample

```ruby
Google::Ads::GoogleAds::Config.new do |c|
  c.developer_token = 'INSERT_DEVELOPER_TOKEN_HERE'
  c.client_id = 'INSERT_CLIENT_ID_HERE'
  c.client_secret = 'INSERT_CLIENT_SECRET_HERE'
  c.refresh_token = 'INSERT_REFRESH_TOKEN_HERE'
  c.login_customer_id = 'INSERT_LOGIN_CUSTOMER_ID_HERE'
end

```

with that been said, then if we update to this new version of the gem, this configuration file should remain without any change at all as it is now cuz all the loopback ip work was solved in this new version rigth and we can continue running our scripts without problem after October 3rd 2022 right?!

Many thanks for your help and the great work you are doing!

Kind regards!

César

**Comment by mcloonan** [comment]
Any existing auth you have should continue to work. If you need to generate a new token, we've also updated our example for how to do that: https://github.com/googleads/google-ads-ruby/blob/main/examples/authentication/generate_user_credentials.rb

You actually don't need to make any changes to your gem or your config (unless you generate new credentials). This change is on the server side.

**Comment by voicelessreason** [comment]
@mcloonan Just to clarify, you are saying that with the new generate_user_credentials code, there is no need to make any changes to our application code if we were to need to generate a new refresh token for any reason? According to google docs OOB will be deprecated soon (https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#dates-oob) and as far as I can tell that's the current methodology we've implemented to retrieve the refresh token. I understand that as long as we don't need to generate new credentials and as long as we continue to get our refresh tokens, there should be no issue. But is it accurate to say that, if we did need new credentials for any reason, that with the latest version of the gem we will be able to simply run generate_user_credentials and have it just work for generating a new one? The last time I had to change credentials I was getting warnings using the old method and had to basically fake a loopback IP (https://stackoverflow.com/a/71331562/8365175 for reference) because the requests were getting rejected. 

What we are trying to avoid is a scenario in which, for whatever reason, after being forced to generate new credentials wind up unable to authorize because our method is non-compliant. If we can get confirmation that we can simply use the example code to get our new refresh code then I think we're in good shape. 

Hope that made sense, thanks for your support.

**Comment by mcloonan** [comment]
I think you're confusing "refresh" and "access" tokens.

The refresh token is generated with user intervention, where you log in on a browser and grant access to your Google Ads account.

Then the refresh token is used by the library to automatically grant short-lived access tokens, which are what are actually used at the time that you access the API to grant access.

This deprecation refers to changing the way that *refresh tokens* are granted, but *access tokens* are unaffected. So, should you need to generate a new refresh token, you'd need to use our new `generate_user_credentials` example. Then, you'd plug that refresh token into your config file like you always have, and the library functionality remains unchanged. The `generate_user_credentials` example actually doesn't user our library at all, but is provided to demonstrate this important step.

You could always try running `generate_user_credentials` now, just to ensure that it works. It (usually) won't affect your current refresh token. If you generate too many refresh tokens, though, the old ones will start being silently deauthorized. I think you can have somewhere around 50 active refresh tokens at a time.

**Comment by voicelessreason** [comment]
Thanks for your informative answer. I believe I was indeed mistaken about what was being deprecated here, and what role this library plays in the process. Thanks again
