### ISSUE TITLE
How to trigger a `remove_all` OfflineUserDataJobOperation?

### ISSUE THREAD

**Issue by alexibz** [googleads/google-ads-ruby#414]
**What is your question?**
I'm trying to figure out how to trigger a [remove_all](https://developers.google.com/google-ads/api/reference/rpc/v11/OfflineUserDataJobOperation) operation on a customer match list. I know how to create and remove resources, but can't `remove_all` using the library, although I see it is part of the spec [here](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v10/services/offline_user_data_job_service.proto#L196) :
Examples using remove and create:
```ruby
google_client.operation.create_resource.offline_user_data_job
google_client.operation.remove_resource.offline_user_data_job
```

**Comment by mcloonan** [comment]
The `create_resource` and etc. are shortcuts that automatically populate the create/remove/update field of the operation, since those are very common across all operation types. For anything else, you should be able to do:

```ruby
google_client.operation.[type] do |op|
  # Code here acting on the operation.
  op.create = client.resource.[type] ...
end
```

Which will then let you operate on the operation directly. So in this case:

```ruby
google_client.operation.offline_user_data_job do |op|
  op.remove_all = true
end
```
