### ISSUE TITLE
Beta API feedback, Client#resource

### ISSUE THREAD

**Issue by dmitchell** [googleads/google-ads-ruby#5]
I believe the resources should define getters and setters for all the attributes which do the appropriate wrapper calls rather than expecting the user of the api to tediously call wrapper as in the following
``` ruby
payload = client.resource(:CampaignBudget)
payload.name = client.wrapper.string(name)
```
which should just be imho
``` ruby
payload.name = name
```

Similarly, resource and operation should take hashes as args and set the corresponding attributes
``` ruby
payload = client.resource(:CampaignBudget, {name: name, amount_micros: amount, delivery_method: 'ACCELERATED', explicitly_shared: true})
```
You'll note that I expect the setter for 'delivery_method' to know how to find its enum and lookup the value. (I'm writing our own shims to do this but would prefer to use yours)

**Comment by mcloonan** [comment]
The proto library recently accepted a pull request that will allow us to bypass the "wrapper" call.

Instead of

    payload.name = client.wrapper.string(name)

you'll be able to use

    payload.name_as_value = name

This is not available yet, but will be in their next gem release.

`payload.name` will still require a `StringValue`, but the `*_as_value` fields will accept primitives and wrap them appropriately for you.

Also, you can set enums using symbol notation, for example:

    campaign_budget.delivery_method = :ACCELERATED

I think the main outstanding usability issue would be getting back enum values as symbols in all cases rather than as numbers in some cases, so I'll leave this open until we have a solution for that.

**Comment by mcloonan** [comment]
Upon further research, it looks like enums actually do return as symbols in all cases. I'm going to close out this bug, but please file any new bugs for any other usability issues you run into.
